### ISSUE TITLE
Robyn Issues List - Ongoing

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2642]
### **Ongoing Issues List** 
- List Starting Summer 2023 
- For issues before summer 2023 please refer to Robyn's issues list for 2023 #2229  

- [ ] Add UNO student hours total to exported data (all) #2624 
- [ ] Fix footer (all of tool) #2625
- [ ] Inconsistent project data between reports #2626
- [ ] Make table view default #2627
- [ ] Unpublish following reports/charts from the tool #2628
- [ ] Improve Mobile Use #2629
- [ ] Wagtail Update 
- [ ] Pull together All Projects and Projects Report Pages #2630
- [ ] Foundation-related data #2631
- [ ] Export Results (limited to page view) #2632
- [ ] Focus area not populating #2633
- [ ] Create/Edit Project Academic Year Reverting Back #2634
- [ ] Data Not Populating to Tables - Community Partner Report #2635
- [ ] Data Not Populating to Tables - Analytics Reports #2636
- [ ] Change color for "Apply Filters" Button #2637
- [ ] Padding Around Gray Buttons - Bottom of Pages #2638
- [ ] Add Return to Top Arrow - Bottom of Pages #2639
- [ ] Change to Community Partner Doesn't Updated #2640
- [ ] Maps Search Not Working #2641

**Comment by robynlloos** [comment]
@MansiKamthan @SachinPawaskarUNO - above are all the issues that are listed on the summer 2023 excel. Mansi I added the ones that are already done but feel free to edit anything within the issues if I missed things.

**Comment by robynlloos** [comment]
@MansiKamthan I have not gotten to the hierarchy of subcategories yet. I am wondering if I should do this in a way that helps us updated the projects as well? Is there a way you can pull all the projects that have a subcategory and remove them?
